apiVersion: ramendr.openshift.io/v1alpha1
kind: RamenConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: 127.0.0.1:9289
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: hub.ramendr.openshift.io
ramenControllerType: dr-hub
maxConcurrentReconciles: 50
volSync:
  destinationCopyMethod: Direct
ramenOpsNamespace: ramen-ops
multiNamespace:
  FeatureEnabled: true
  volsyncSupported: true
kubeObjectProtection:
  veleroNamespaceName: velero
