resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- ../../rbac/service_account.yaml
- role.yaml
- role_binding.yaml
- ../../rbac/leader_election_role.yaml
- ../../rbac/leader_election_role_binding.yaml
# Comment the following 4 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
- ../../rbac/auth_proxy_service.yaml
- ../../rbac/auth_proxy_role.yaml
- ../../rbac/auth_proxy_role_binding.yaml
- ../../rbac/auth_proxy_client_clusterrole.yaml
- ../../rbac/metrics_role.yaml
