## Append samples you want in your CSV to this file as resources ##
resources:
- ramendr_v1alpha1_volumereplicationgroup.yaml
- ramendr_v1alpha1_clusterpeers.yaml
- ramendr_v1alpha1_applicationvolumereplication.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
