## Append samples you want in your CSV to this file as resources ##
resources:
- ramendr_v1alpha1_drcluster.yaml
- ramendr_v1alpha1_protectedvolumereplicationgrouplist.yaml
- ramendr_v1alpha1_maintenancemode.yaml
- ramendr_v1alpha1_drclusterconfig.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
