# Adds namespace to all resources.
namespace: ramen-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: ramen-dr-cluster-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

transformers:
- |-
  apiVersion: builtin
  kind: LabelTransformer
  metadata:
    name: temporary
  labels:
    app: ramen-dr-cluster
  fieldSpecs:
  - kind: Deployment
    path: metadata/labels
  - kind: Deployment
    path: spec/selector/matchLabels
  - kind: Deployment
    path: spec/template/metadata/labels
  - kind: Service
    path: metadata/labels
  - kind: Service
    path: spec/selector

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
# crd/kustomization.yaml
#- ../webhook
# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER'. 'WEBHOOK' components are required.
#- ../certmanager
# [PROMETHEUS] To enable prometheus monitor, uncomment all sections with 'PROMETHEUS'.
#- ../prometheus

# Protect the /metrics endpoint by putting it behind auth.
# If you want your controller-manager to expose the /metrics
# endpoint w/o any authn/z, please comment the following line.

# Mount the controller config file for loading manager configurations
# through a ComponentConfig type
patchesStrategicMerge:
- ../../default/manager_auth_proxy_patch.yaml
- ../../default/manager_config_patch.yaml

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
# crd/kustomization.yaml
#- manager_webhook_patch.yaml

# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER'.
# Uncomment 'CERTMANAGER' sections in crd/kustomization.yaml to enable the CA injection in the admission webhooks.
# 'CERTMANAGER' needs to be enabled to use ca injection
#- webhookcainjection_patch.yaml

# the following config is for teaching kustomize how to do var substitution
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../crd
- ../rbac
- ../manager
images:
- name: kube-rbac-proxy
  newName: gcr.io/kubebuilder/kube-rbac-proxy
  newTag: v0.8.0
