
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: applicationvolumereplications.ramendr.openshift.io
spec:
  group: ramendr.openshift.io
  names:
    kind: ApplicationVolumeReplication
    listKind: ApplicationVolumeReplicationList
    plural: applicationvolumereplications
    singular: applicationvolumereplication
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ApplicationVolumeReplication is the Schema for the ApplicationVolumeReplications
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ApplicationVolumeReplicationSpec defines the desired state
              of ApplicationVolumeReplication
            properties:
              failedCluster:
                type: string
            type: object
          status:
            description: ApplicationVolumeReplicationStatus defines the observed state
              of ApplicationVolumeReplication
            properties:
              statuses:
                additionalProperties:
                  description: SubscriptionPlacementDecision lists each subscription
                    with its home and peer clusters
                  properties:
                    homeCluster:
                      type: string
                    peerCluster:
                      type: string
                  type: object
                description: Decisions are for subscription and by AVR namespace (which
                  is app namespace)
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
